### ISSUE TITLE
Support VST 3.7.8

### ISSUE THREAD

**Issue by cbix** [igorski/regrader#14]
On Linux with VST 3.7.8, these errors are thrown during build:
```
[ 66%] Building CXX object CMakeFiles/regrader.dir/src/vstentry.cpp.o
[ 70%] Building CXX object CMakeFiles/regrader.dir/src/ui/controller.cpp.o
In file included from /home/florian/build/igorski/regrader/src/ui/controller.cpp:25:
/home/florian/build/igorski/regrader/src/ui/uimessagecontroller.h: In member function ‘void Steinberg::Vst::RegraderUIMessageController<T>::setMessageText(Steinberg::Vst::TChar*)’:
/home/florian/build/igorski/regrader/src/ui/uimessagecontroller.h:60:20: error: expected primary-expression before ‘str’
   60 |             String str( msgText );
      |                    ^~~
/home/florian/build/igorski/regrader/src/ui/uimessagecontroller.h:61:13: error: ‘str’ was not declared in this scope; did you mean ‘std’?
   61 |             str.toMultiByte( kCP_Utf8 );
      |             ^~~
      |             std
/home/florian/build/igorski/regrader/src/ui/uimessagecontroller.h:61:30: error: ‘kCP_Utf8’ was not declared in this scope
   61 |             str.toMultiByte( kCP_Utf8 );
      |                              ^~~~~~~~
/home/florian/build/igorski/regrader/src/ui/uimessagecontroller.h: In member function ‘Steinberg::Vst::RegraderUIMessageController<T>::CView* Steinberg::Vst::RegraderUIMessageController<T>::verifyView(CView*, const VSTGUI::UIAttributes&, const VSTGUI::IUIDescription*)’:
/home/florian/build/igorski/regrader/src/ui/uimessagecontroller.h:114:24: error: expected primary-expression before ‘str’
  114 |                 String str( regraderController->getDefaultMessageText());
      |                        ^~~
/home/florian/build/igorski/regrader/src/ui/uimessagecontroller.h:115:17: error: ‘str’ was not declared in this scope; did you mean ‘std’?
  115 |                 str.toMultiByte (kCP_Utf8);
      |                 ^~~
      |                 std
/home/florian/build/igorski/regrader/src/ui/uimessagecontroller.h:115:34: error: ‘kCP_Utf8’ was not declared in this scope
  115 |                 str.toMultiByte (kCP_Utf8);
      |                                  ^~~~~~~~
/home/florian/build/igorski/regrader/src/ui/uimessagecontroller.h: In member function ‘void Steinberg::Vst::RegraderUIMessageController<T>::viewLostFocus(CView*)’:
/home/florian/build/igorski/regrader/src/ui/uimessagecontroller.h:138:24: error: expected primary-expression before ‘str’
  138 |                 String str;
      |                        ^~~
/home/florian/build/igorski/regrader/src/ui/uimessagecontroller.h:139:17: error: ‘str’ was not declared in this scope; did you mean ‘std’?
  139 |                 str.fromUTF8 (text.data ());
      |                 ^~~
      |                 std
make[2]: *** [CMakeFiles/regrader.dir/build.make:255: CMakeFiles/regrader.dir/src/ui/controller.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/regrader.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

Are there plans to keep supporting later vst3sdk versions or is it simply recommended to stay on 3.7.6 (which still has some other issues on later gcc versions that have since been fixed).

Also it would be great to have release tags on the git repo so we can properly package this for Arch Linux :)

**Comment by igorski** [comment]
Hi @cbix it took a while but I am now looking into updating / maintaining all VST plugins.

Your request was originally for 3.7.8 but I have been working with the latest available version [3.7.9 build 61](https://github.com/steinbergmedia/vst3sdk/releases/tag/v3.7.9_build_61), assuming the minor version jump isn't an issue for you.

I have so far refactored the code to handle deprecations of the SDK and built on macOS. Could you verify whether branch [379](https://github.com/igorski/regrader/tree/379) works for your Linux distribution ?

**Comment by cbix** [comment]
> Could you verify whether branch [379](https://github.com/igorski/regrader/tree/379) works for your Linux distribution ?

Build works here with VST 3.7.9, nice! Still having some issues running the full SDK build, but the necessary parts build successfully.

**Comment by igorski** [comment]
Hi @cbix thanks for the verification. But just to confirm : is it working or not ? You mention it builds, but are still having issues with the full SDK build ?

**Comment by cbix** [comment]
@igorski it works in Ardour and Reaper but isn't even found in Carla for some reason. By full SDK build I mean vst3sdk build fails after some time but after the objects needed by regrader are already built, so the regrader build succeeds.

**Comment by tank-trax** [comment]
Can I ask, why are you using Steinberg's crappy SDK instead of building using JUCE?

**Comment by tank-trax** [comment]
Have you considered using JUCE rather than Steinberg's VST3 SDK for your plugins?

**Comment by igorski** [comment]
@tank-trax 

> Have you considered using JUCE rather than Steinberg's VST3 SDK for your plugins?

Honestly, not when initially building them as Steinbergs SDK is well documented (and heck, _they invented the format_, didn't they) ? But over the years I've come disappointed with cross platform stability of the SDK updates and breaking API changes on what are _minor_ version bumps.

It's unlikely I will port Regrader to JUCE, but a future project might use it. Depending on ease of implementation I can consider a migration for the older plugins built using Steinbergs SDK.

**Comment by tank-trax** [comment]
I am on Linux and Linux is complicated. That being said I am using your plugins now with WINE and they work great, but needing to use the generic GUI as the knobs (although they work) do not display. DSP is great using this method.

Thanks

**Comment by cbix** [comment]
@tank-trax which distro are you on?

**Comment by tank-trax** [comment]
Debian 12, KDE Plasma, X11 or Wayland, using Pipewire

**Comment by igorski** [comment]
@cbix does the build work using VST 3.7.10 (see latest release tag in this repo) ?

**Comment by cbix** [comment]
@igorski with vst3sdk 3.7.10 I'm getting this error:
```
[ 75%] Building CXX object CMakeFiles/regrader.dir/home/florian/build/vst3sdk/public.sdk/source/main/linuxmain.cpp.o
make[2]: *** No rule to make target '/home/florian/build/vst3sdk/build/lib/Release/libbase.a', needed by 'VST3/None/regrader.vst3/Contents/x86_64-linux/regrader.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/regrader.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
I'm building explicitly with `-DCMAKE_BUILD_TYPE=None` and the static libs are actually under `vst3sdk/build/lib` but for some reason they are expected under `Release`.

**Comment by igorski** [comment]
@cbix interesting, the libs are organized by build type but maybe that is probably generator specific.

I have created branch `linux-build` to address this (also see [pull request #19](https://github.com/igorski/regrader/pull/19). Can you verify whether builds using that branch work for you ?

**Comment by cbix** [comment]
I think independent of the branch it seems to expect that vst3sdk has a `build` directory with everything precompiled, instead of integrating the build steps.

That said, the `linux-build` branch works if I precompile vst3sdk 3.7.12 (3.7.10 has some issues)

**Comment by igorski** [comment]
> it seems to expect that vst3sdk has a build directory with everything precompiled

Well, that is listed as a prerequisite in the README `Be aware that prior to building the plugin, the Steinberg SDK needs to be built from source as well`.

I understand its a bit cumbersome and its one of the reasons that newer plugins will be developed using JUCE (Steinbergs SDK updates have been notoriously ... _difficult_ even during minor versions changes). I will however have a look at using SDK `3.7.12` to also solve a parallel issue (broken Audio Unit builds).

**Comment by tank-trax** [comment]
The Surge Synth Team ported Surge from vstgui to JUCE. It wasn't trivial but it was doable. 

It's not out of the realm of possibilities to port your apps to JUCE. If you'd like some help or insights please join our Discord server.

**Comment by igorski** [comment]
I have btw updated the repo to include a `setup.sh` script which will fetch and install a local version of the SDK which should make things a little easier, though it currently targets `3.7.11` instead of `3.7.12` (as a related development to support AUv3 builds would not work on the 12 version).

Either way it should be easier to manage this uniformly going forwards which should alleviate any difficulties related to different setups and SDK versions, hopefully.

Going from Steinberg SDK to JUCE is indeed `not trivial but doable` as you say, but it requires some time and effort for an otherwise complete plugin. I understand it will be easier for the Linux community (as providing precompiled binaries for different distributions is an altogether more difficult distribution method) so never say never but I will have to be honest and say that has a lower priority for now.
